config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    resources :answers, only: [:edit, :create, :destroy, :update] do
        put 'like', to: 'answers#upvote'
        put 'dislike', to: 'answers#downvote'
      end
    end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]


end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates :user, presence: :true
  validates :question, presence: :true
  validates :body, presence: :true

  acts_as_votable
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true
  paginates_per 10
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: :true, uniqueness: true
    validates :password, length: { minimum: 8}, on: :create
    has_secure_password
    acts_as_voter
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:edit, :update, :destroy]

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.user_id = session[:user_id]
    @answer.question_id = params[:answer][:question_id]
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer.question, notice: 'Thanks for your contribution–Answer was saved!' }
        format.json { render :show, status: :created, location: @answer.question }
      else
        format.html { redirect_to @answer.question, notice: 'Error: Answer was not saved.' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer.question, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer.question }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @question = @answer.question
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:answer_id])
    @answer.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:answer_id])
    @answer.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @q = Question.ransack(params[:q])
    @results = @q.result.page(params[:page]).order("created_at desc")
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
    @answers = Answer.where(question: @question).order(:cached_votes_up => :desc)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :current_user

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(current_user)
    else
      flash[:incorrect_log_in] = "Incorrect name or password"
      render 'sessions/new', status: 401
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :current_user
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @questions = Question.where(user: @user)
    @answers = Answer.where(user: @user)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.haml
= form_for @answer, url: { action: "update" } do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2
        = pluralize(@answer.errors.count, "error")
        prohibited this answer from being saved:
      %ul
        - @answer.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    .btn.btn-default
      = f.submit  "Update"

app/views/answers/edit.html.haml
%h1 Editing Answer
- if @answer.user == current_user
    = render 'form'
- else
    %p This isn't your question!
\#{link_to 'Back', question_answers_path}

app/views/layouts/_navbar.html.erb
<%= nav_bar brand: "LFOxchange", responsive: true do %>
  <%= menu_group do %>
      <%= menu_item "Home", root_path %>
      <%= menu_divider %>
      <%= drop_down "--" do %>
        <% if current_user %>
          <%= menu_item 'New Question', new_question_path %>
          <%= menu_item "Your Account", user_path(current_user) %>
          <%= menu_item "Logout", session_path(session[:user_id]), method: :delete if session[:user_id] %>
        <% else %>
          <%= menu_item "Log In", new_session_path %>
        <% end %>
    <% end %>
    <%= menu_group pull: :right do %>
      <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Lfox
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: "layouts/navbar"
    .col-xs-6.col-md-4
    .col-xs-7.col-md-5
      = yield

app/views/questions/_answer_form.html.haml
= form_for @answer, url:  question_answers_path(@question.id) do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2
        = pluralize(@answer.errors.count, "error")
        prohibited this answer from being saved:
      %ul
        - @answer.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label "Your Answer:"
    %br/
    = f.text_area :body
    %br/
    = f.hidden_field :question_id, :value => params[:id]
  .btn
    = f.submit

app/views/questions/_form.html.haml
= form_for(@question) do |f|
  - if @question.errors.any?
    #error_explanation
      %h2
        = pluralize(@question.errors.count, "error")
        prohibited this question from being saved:
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit

app/views/questions/edit.html.haml
%h1 Editing Question
= render 'form'
\#{link_to 'Back', questions_path}

app/views/questions/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<ul>

<%= search_form_for @q do |f| %>
  <div class="field">
    <%= f.label "Search:" %>
    <%= f.search_field :title_or_body_cont %>
  <div class="btn">
    <%= f.submit %>
  </div>
  </div>
<% end %>

<h4>Most Recent Questions:</h4>
  <% @results.each do |question| %>
    <li>
      <strong><%= link_to question.title.to_s, question %></strong>
        Answers Given: <%= question.answers.count %>
    </li>
    <% if question.user == current_user %>
      <ul>
        <li>
          <%= link_to 'Edit', edit_question_path(question) %>
        </li>
        <li>
          <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
      </ul>
    <% end %>
  <% end %>
</ul>
<div>
  <%= paginate @results %>
</div>

app/views/questions/new.html.haml
%h1 Your Question:
= render 'form'
\#{link_to 'Back', questions_path}

app/views/questions/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>
<p>
  <strong>User:</strong>
  <%= @question.user.name %>
</p>
<% if @question.user == current_user %>
  <%= link_to 'Edit', edit_question_path(@question) %>
|
<% end %>
<%= link_to 'Back', questions_path %>
<% if !@answers.empty? %>
  <% @answers.each do |answer| %>
    <ul>
      <li><%= answer.body %></li>
      <li><%= answer.user.name %></li>
      <% if answer.user == current_user %>
        <li><%= link_to 'Edit', edit_question_answer_path(@question, answer) %></li>
        <li><%= link_to 'Destroy', question_answer_path(@question, answer), method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
      <li><%= answer.get_upvotes.size %></li>
      <% if current_user %>
        <% if current_user.voted_up_on?(answer) %>
          <li><%= link_to 'UnVote', question_answer_dislike_path(@question, answer.id), method: :put %></li>
        <% else %>
          <li><%= link_to 'UpVote', question_answer_like_path(@question, answer.id), method: :put %></li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
<% end %>
<%  if current_user %>
  <%= render 'answer_form' %>
<% end %>

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :password
    %br/
    = f.text_field :password
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
\#{link_to 'Back', users_path}

app/views/users/index.html.haml
%p#notice= notice
%h1 Listing Users
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
  <% unless @questions.empty? %>
    <h2>Questions: </h2>
      <% @questions.each do |question| %>
        <ul>
          <li><%= link_to question.title, question_path %></li>
        </ul>
      <% end %>
    <% else %>
      <h3>No questions yet!</h3>
    <% end %>
  <% unless @answers.empty? %>
    <h2>Questions: </h2>
      <% @answers.each do |answer| %>
        <ul>
          <li><%= link_to answer.body[0..30].gsub(/\s\w+\s*$/, '...'), question_path(answer.question.id) %></li>
        </ul>
      <% end %>
    <% else %>
      <h3>No questions yet!</h3>
    <% end %>
</p>